version: '3'

services:
  db:
    image: postgres
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: post_manager
    volumes:
      - db_data:/var/lib/postgresql/data

volumes: 
  db_data: